require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - microformats.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
